# ESCREVA UM PROGRAMA QUE PERGUNTE O SALÁRIO DE UM FUNCIONÁRIO
# E CALCULE O VALOR DO SEU AUMENTO.

# PARA SALÁRIOS SUPERIORES A R$1.250,00, CALCULE UM AUMENTO
# DE 10%.

# PARA OS INFERIORES OU IGUAIS, O AUMENTO É DE 15%.